<?php

namespace ContainerNkMGbdr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Rm4mf66Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Rm4mf66' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Rm4mf66'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'engineeringOfficeSortRepository' => ['privates', 'App\\Repository\\EngineeringOfficeSortRepository', 'getEngineeringOfficeSortRepositoryService', true],
        ], [
            'engineeringOfficeSortRepository' => 'App\\Repository\\EngineeringOfficeSortRepository',
        ]);
    }
}
