<?php

namespace ContainerCbE7gbx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WOHcRd0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wOHcRd0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wOHcRd0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'engineeringOfficeSortRepository' => ['privates', 'App\\Repository\\EngineeringOfficeSortRepository', 'getEngineeringOfficeSortRepositoryService', true],
            'managerRegistry' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'engineeringOfficeSortRepository' => 'App\\Repository\\EngineeringOfficeSortRepository',
            'managerRegistry' => '?',
        ]);
    }
}
