<?php

namespace ContainerNGpFJEm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q2hdW62Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Q2hdW62' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Q2hdW62'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'employeeRepository' => ['privates', 'App\\Repository\\EmployeeRepository', 'getEmployeeRepositoryService', true],
        ], [
            'employeeRepository' => 'App\\Repository\\EmployeeRepository',
        ]);
    }
}
