<?php

namespace ContainerNGpFJEm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AqfwKkFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AqfwKkF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AqfwKkF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'projectAccessRepository' => ['privates', 'App\\Repository\\ProjectAccessRepository', 'getProjectAccessRepositoryService', true],
            'projectRepository' => ['privates', 'App\\Repository\\ProjectRepository', 'getProjectRepositoryService', true],
        ], [
            'projectAccessRepository' => 'App\\Repository\\ProjectAccessRepository',
            'projectRepository' => 'App\\Repository\\ProjectRepository',
        ]);
    }
}
