<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'home.fr' => [[], ['_controller' => 'App\\Controller\\HomeController::index', '_locale' => 'fr', '_canonical_route' => 'home'], [], [['text', '/']], [], []],
    'home.en' => [[], ['_controller' => 'App\\Controller\\HomeController::index', '_locale' => 'en', '_canonical_route' => 'home'], [], [['text', '/en/']], [], []],
    'project.fr' => [['id'], ['_controller' => 'App\\Controller\\ProjectController::show', '_locale' => 'fr', '_canonical_route' => 'project'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/projet']], [], []],
    'project.en' => [['id'], ['_controller' => 'App\\Controller\\ProjectController::show', '_locale' => 'en', '_canonical_route' => 'project'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/en/project']], [], []],
    'security_signin.fr' => [[], ['_controller' => 'App\\Controller\\SecurityController::signin', '_locale' => 'fr', '_canonical_route' => 'security_signin'], [], [['text', '/inscription']], [], []],
    'security_signin.en' => [[], ['_controller' => 'App\\Controller\\SecurityController::signin', '_locale' => 'en', '_canonical_route' => 'security_signin'], [], [['text', '/en/signin']], [], []],
    'security_login.fr' => [[], ['_controller' => 'App\\Controller\\SecurityController::login', '_locale' => 'fr', '_canonical_route' => 'security_login'], [], [['text', '/connexion']], [], []],
    'security_login.en' => [[], ['_controller' => 'App\\Controller\\SecurityController::login', '_locale' => 'en', '_canonical_route' => 'security_login'], [], [['text', '/en/login']], [], []],
    'security_logout.fr' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout', '_locale' => 'fr', '_canonical_route' => 'security_logout'], [], [['text', '/deconnexion']], [], []],
    'security_logout.en' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout', '_locale' => 'en', '_canonical_route' => 'security_logout'], [], [['text', '/en/logout']], [], []],
];
