<?php

namespace ContainerZhtUYqA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_GA7XnyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored.GA7_xny' shared service.
     *
     * @return \App\Entity\Project
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\ProjectController::show()": the $project argument is type-hinted with the non-existent class or interface: "App\\Entity\\Project".');
    }
}
