<?php

namespace Container1CtYxGo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8wwEOn0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8wwEOn0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8wwEOn0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'projectCommentRepository' => ['privates', 'App\\Repository\\ProjectCommentRepository', 'getProjectCommentRepositoryService', true],
            'projectRepository' => ['privates', 'App\\Repository\\ProjectRepository', 'getProjectRepositoryService', true],
        ], [
            'projectCommentRepository' => 'App\\Repository\\ProjectCommentRepository',
            'projectRepository' => 'App\\Repository\\ProjectRepository',
        ]);
    }
}
