<?php

namespace ContainerVkITcZ1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IELWDsQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IELWDsQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IELWDsQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'managerRegistry' => ['services', 'doctrine', 'getDoctrineService', false],
            'workRepository' => ['privates', 'App\\Repository\\WorkRepository', 'getWorkRepositoryService', true],
        ], [
            'managerRegistry' => '?',
            'workRepository' => 'App\\Repository\\WorkRepository',
        ]);
    }
}
