<?php

namespace ContainerVkITcZ1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CteDwzwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CteDwzw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CteDwzw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'engineeringofficeRepository' => ['privates', 'App\\Repository\\EngineeringOfficeRepository', 'getEngineeringOfficeRepositoryService', true],
        ], [
            'engineeringofficeRepository' => 'App\\Repository\\EngineeringOfficeRepository',
        ]);
    }
}
