<?php

namespace ContainerVkITcZ1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Lx3Oc0pService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Lx3Oc0p' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Lx3Oc0p'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'departmentRepository' => ['privates', 'App\\Repository\\DepartmentRepository', 'getDepartmentRepositoryService', true],
        ], [
            'departmentRepository' => 'App\\Repository\\DepartmentRepository',
        ]);
    }
}
