<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCbE7gbx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCbE7gbx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCbE7gbx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCbE7gbx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCbE7gbx\App_KernelDevDebugContainer([
    'container.build_hash' => 'CbE7gbx',
    'container.build_id' => '93de85f7',
    'container.build_time' => 1624040673,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCbE7gbx');
