<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSyaiWtl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSyaiWtl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSyaiWtl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSyaiWtl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSyaiWtl\App_KernelDevDebugContainer([
    'container.build_hash' => 'SyaiWtl',
    'container.build_id' => 'd3b524d4',
    'container.build_time' => 1624230237,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSyaiWtl');
