<?php

namespace ContainerB0GSx7g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MrEJIwAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mrEJIwA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mrEJIwA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'engineeringofficeRepository' => ['privates', 'App\\Repository\\EngineeringOfficeRepository', 'getEngineeringOfficeRepositoryService', true],
            'managerRegistry' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'engineeringofficeRepository' => 'App\\Repository\\EngineeringOfficeRepository',
            'managerRegistry' => '?',
        ]);
    }
}
