<?php

namespace ContainerB0GSx7g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_01Z0d64Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.01Z0d64' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.01Z0d64'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'managerRegistry' => ['services', 'doctrine', 'getDoctrineService', false],
            'personContactRepository' => ['privates', 'App\\Repository\\PersonContactRepository', 'getPersonContactRepositoryService', true],
            'projectRepository' => ['privates', 'App\\Repository\\ProjectRepository', 'getProjectRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'mailer' => '?',
            'managerRegistry' => '?',
            'personContactRepository' => 'App\\Repository\\PersonContactRepository',
            'projectRepository' => 'App\\Repository\\ProjectRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
