<?php

namespace ContainerB0GSx7g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SJz_JzMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sJz.jzM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sJz.jzM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'roleRepository' => ['privates', 'App\\Repository\\RoleRepository', 'getRoleRepositoryService', true],
        ], [
            'roleRepository' => 'App\\Repository\\RoleRepository',
        ]);
    }
}
