<?php

namespace ContainerB0GSx7g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__QT1yBQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..qT1yBQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..qT1yBQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'encoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService', true],
            'managerRegistry' => ['services', 'doctrine', 'getDoctrineService', false],
            'personContactRepository' => ['privates', 'App\\Repository\\PersonContactRepository', 'getPersonContactRepositoryService', true],
            'projectRepository' => ['privates', 'App\\Repository\\ProjectRepository', 'getProjectRepositoryService', true],
            'userSigninSecurityRepository' => ['privates', 'App\\Repository\\UserSigninSecurityRepository', 'getUserSigninSecurityRepositoryService', true],
        ], [
            'encoder' => '?',
            'managerRegistry' => '?',
            'personContactRepository' => 'App\\Repository\\PersonContactRepository',
            'projectRepository' => 'App\\Repository\\ProjectRepository',
            'userSigninSecurityRepository' => 'App\\Repository\\UserSigninSecurityRepository',
        ]);
    }
}
